### ISSUE TITLE
hg38 to T2T v1.1 liftOver

### ISSUE THREAD

**Issue by Nurpe** [broadinstitute/liftover#1]
Hello, 
I am interested in changing some samples from hg38 to T2T v1.1, but in https://liftover.broadinstitute.org I see that it can only be done one at a time. Is there any way to pass more data together?

Thank you

**Comment by bw2** [comment]
liftover.broadinstitute.org works by running the UCSC liftover tool for each input (using [this command](https://github.com/broadinstitute/SpliceAI-lookup/blob/master/server.py#L441) ). The most efficient way to process many inputs would be for you to run the command-line tool directly on your data. 

(If you want to convert intervals, the UCSC liftover tool is best - it can be downloaded from [http://hgdownload.soe.ucsc.edu/admin/exe/](http://hgdownload.soe.ucsc.edu/admin/exe/). If you want to convert variants, I would use [gatk LiftoverVCF](https://gatk.broadinstitute.org/hc/en-us/articles/360037060932-LiftoverVcf-Picard-). The chain files can be downloaded from the comment by slw287r 
 @  https://github.com/marbl/CHM13/issues/29 ).

**Comment by Nurpe** [comment]
Done! Thanks.
