### ISSUE TITLE
Batch liftover using HGVS nomenclature

### ISSUE THREAD

**Issue by emjblake** [broadinstitute/liftover#12]
Would it be possible to request functionality to batch liftover variants in HGVS notation? The UCSC liftover tool only uses BED format and the GATK LiftoverVcf uses VCF/BED format. Thanks!

**Comment by bw2** [comment]
No, that would require significant modifications. 
liftover.broadinstitute.org currently uses an Ensembl API to convert a variant from HGVS to chrom-pos-ref-alt, 
and that API handles one variant at a time. For batch processing, I would recommend writing a script using a library like https://github.com/biocommons/hgvs or just running VEP on your variants.
