### ISSUE TITLE
liftover error message

### ISSUE THREAD

**Issue by fabmau** [broadinstitute/liftover#13]
Hi,
regardless of the input, I am receiving an error message when attempting to use the online liftover tool

URL: https://liftover.broadinstitute.org/
Example of input query: 19 33882259 G A
Liftover mode: hg19 -> hg38
Error message received: ERROR: An unknown error occurred.
Browsers tested: Chrome and Edge (on Windows, obviously)

Any explanation for that ?
Thank you,
Fabienne

**Comment by NM-G08** [comment]
My team noticed the error as of yesterday in case that helps in any way.

**Comment by bw2** [comment]
Apologies, this should now be fixed. 
There was a configuration issue on the server which I didn't notice until now.
