### ISSUE TITLE
Issues with liftOver as of recently

### ISSUE THREAD

**Issue by francesca-procopio** [broadinstitute/liftover#14]
Hi,
I hope you are well. I am a PhD student at King's College London, and we have been using the liftOver executable file to change the build of our summary statistics when creating polygenic scores using LDPred2. However, we have recently started to have issues with downloading the chain file, which we never have before. When we use this line of code of the script: 

sumstats <- snp_modifyBuild(sumstats, '/path/to/file/liftOver', from = 'hg19', to = 'hg38') 

We get error messages stating that the file was not able to be download (see below). We don't think it is an issue with our server, however we do not know why this is happening. Do you have any thoughts?
Thank you so much.

Error message: 
Loading required package: bigstatsr
Attaching package: ‘dplyr’
The following objects are masked from ‘package:data.table’:
  between, first, last
The following objects are masked from ‘package:stats’:
  filter, lag
The following objects are masked from ‘package:base’:
  intersect, setdiff, setequal, union
Error in utils::download.file(url, destfile = chain, quiet = TRUE) :
 cannot open URL 'ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz'
Calls: snp_modifyBuild -> <Anonymous>
In addition: Warning message:
In utils::download.file(url, destfile = chain, quiet = TRUE) :
 URL 'ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz': Timeout of 60 seconds was reached
Execution halted

**Comment by bw2** [comment]
Hi @francesca-procopio , I think this issue was posted in the wrong github repo. 
There is no R code here. 
Perhaps it was meant for https://github.com/privefl/bigsnpr ?
