### ISSUE TITLE
Liftover tool is not working: ERROR: An unknown error occurred.

### ISSUE THREAD

**Issue by mjlarsen** [broadinstitute/liftover#2]
Hi
The liftover tools is not working. No matter what input is used it gives the following error:

`ERROR: An unknown error occurred.

Best,
Martin

**Comment by bw2** [comment]
I'm not able to reproduce this error. If you're continuing to see it, please share an input that causes it. 

Thanks
-Ben

**Comment by mjlarsen** [comment]
Hi Ben
That is strange. Even your own example inputs gives me that error: e.g. chr8:141310715

**Comment by bw2** [comment]
What browser and operating system are you using?

**Comment by mjlarsen** [comment]
Hi
I is from my Windows 10 PC using Chrome or Egde. My colleagues are having
the same problem. However, I just tested from my Mac. Here everything is
fine.
Best,
Martin


Den man. 14. mar. 2022 kl. 18.05 skrev bw2 ***@***.***>:
