### ISSUE TITLE
how to  obtain chain information from any two assemblies

### ISSUE THREAD

**Issue by zhoudreames** [broadinstitute/liftover#3]
I want to obtain the chain information from my assemblies,how to get it, thanks~

**Comment by bw2** [comment]
If you're looking for chain files, they are available from the UCSC browser - for example at https://hgdownload.cse.ucsc.edu/goldenpath/hg19/liftOver/

**Comment by zhoudreames** [comment]
thanks for your reply, Can I create this file myself？ I want to use my assembled genome to liftover  ref genome

**Comment by bw2** [comment]
interesting. Yes, it should be possible to create a liftover chain file - for example from a VCF, but I don't have any prior experience with this. You may find this thread to be relevant https://github.com/marbl/CHM13/issues/15 - it talks about the chain file recently created for the t2t assembly.

**Comment by zhoudreames** [comment]
thanks~
