### ISSUE TITLE
error when using liftover tool

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/liftover#4]
I got an error when searching these coordinates for Hg19-->HG38: 
"chr22:18890162-21900621
![liftover_error](https://user-images.githubusercontent.com/47390031/177414536-612bc793-e570-418c-adb7-cc12b119acf0.PNG)
"

**Comment by bw2** [comment]
This is an error message from the UCSC liftOver tool. Below is an explanation of this and other errors (source: https://bioinformaticsonline.com/blog/view/36870/understanding-liftover).

```
Split in new:
    Sequence insufficiently intersects multiple chains
Deleted in new:
    Sequence intersects no chains
Partially deleted in new:
    Sequence insufficiently intersects one chain
Duplicated in new:
    Sequence sufficiently intersects multiple chains
Boundary problem:
    Missing start or end base in an exon
```
