### ISSUE TITLE
HG19 means many different things.  Exactly which references will this liftover?  

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/liftover#5]
There are [at least 4 different versions of "HG19"](https://gatk.broadinstitute.org/hc/en-us/articles/360035890711-GRCh37-hg19-b37-humanG1Kv37-Human-Reference-Discrepancies), and several different versions of HG38 floating around out there.

Can you provide more details as to which of these are actually being used as the liftover references?

**Comment by bw2** [comment]
The liftover tool only takes the UCSC chain files as input and not the full reference fasta. To answer this question, you will need to look into how UCSC generates liftover chain files.
