### ISSUE TITLE
Liftover not reversible 

### ISSUE THREAD

**Issue by xbwdk** [broadinstitute/liftover#6]
Hi liftover team,

I met a weird problem while using the liftover tool. Here is an example: 

hg19 => hg38:
chr7:61819135-61819154 => chr7:62374884-62374903

However, if I input this hg38 coordinate and convert it back to hg19, it returns an error:
hg38 => hg19
chr7:62374884-62374903 =>
'hg38-to-hg19 liftover failed for chr7:62374884-62374903 Deleted in new'

I checked the sequence base by base in the UCSC browser and these two sequences are identical even for +-10bp flanking regions. So I am really confused why the liftover is not reversible here, is it a technical error or there's any logic underlying this scenario?

Thanks.

**Comment by bw2** [comment]
This region has many segmental duplications. If I had to guess, it may be that the number of copies differ between hg19 and hg38. This website just runs the UCSC liftover tool and reports the results, so I can't provide an in-depth explanation.
