### ISSUE TITLE
T2T to hg38

### ISSUE THREAD

**Issue by greekkey** [broadinstitute/liftover#7]
Hi. I lifted several variants from hg38 to T2T. 
Is it possible to do a T2T to hg38 liftover?

**Comment by KL-Cardiff** [comment]
Hi,

I am also having trouble with this as all my mapping data is against the T2T v2 reference and I need to back compare with some hg38 data.  Please can someone advise me as to how I can convert T2T v2 coordinates to hg38 locations?  I just receive failure messages using the UCSC liftover webtool.  Many thanks.

**Comment by bw2** [comment]
I've now added this option.
