### ISSUE TITLE
Liftover hg19>hg38 of BCORL1 not working for mutation NM_001184772:c.4497_4498insGGGGGGGGGT(p.L1499fs)

### ISSUE THREAD

**Issue by carinelegrand** [broadinstitute/liftover#9]
Dear Liftover Team,

While using Liftover for a list of genomic positions, I stumbled on the following error for BCORL1 : 

- Position parsed in hg19 : NM_001184772(BCORL1):c.4497_4498insGGGGGGGGGT(p.L1499fs)
- Error message :  "Unable to parse HGVS notation 'NM_001184772:c.4497_4498insGGGGGGGGGT(p.L1499fs)': Could not get a Transcript object for 'NM_001184772'"

However:

- This transcript exists and has the same RefSeq name in hg19 and hg38 (hg19 : http://genome.ucsc.edu/cgi-bin/hgTracks?position=chrX:129104955-129202046&hgsid=1693792388_16VqI2FQdDkcoxaB3EaBspNuxF2X&refSeqComposite=pack ; hg38 : http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&c&hgt.customText=https://www.genecards.org/all_genecards_v5.17.txt&position=chrX:129970313-130068071&dgvPlus=pack)
- In another software, the mutation is found to exist as g:130034646_130034647insGGGGGGGGGT in hg38

While looking for another mutation in the same gene, I stumbled again on the same error message (position in hg19 : NM_001184772(BCORL1):c.A1111C:p.T371P  ;  position given by other software in hg38 : chrX, g.130013883A>C).

- [ ] -> is there a problem specifically for this gene BCORL1 in liftover ?
- [ ] -> is there a workaround to obtain the hg38 coordinates using LiftOver ?

Many thanks in advance for your help, and best regards,
Carine Legrand

**Comment by bw2** [comment]
Hi Carine, the liftover tool relies on the Ensembl VEP api to parse HGVS notation - in this case:
https://grch37.rest.ensembl.org/vep/human/hgvs/NM_001184772(BCORL1):c.4497_4498insGGGGGGGGGT(p.L1499fs)?content-type=application/json&vcf_string=1

I'm not sure why this doesn't recognize the transcript, while the hg38 version of the api does.
Also, just using the gene name appears to work: `BCORL1:c.4497_4498insGGGGGGGGGT(p.L1499fs)`
